  // Sample data for demonstration
export const healthData = [
  { day: 'Today', period: 'Morning', value: 69 },
  { day: 'Today', period: 'Afternoon', value: 72 },
  { day: 'Today', period: 'Evening', value: 68 },
  { day: 'Tmrw', period: 'Morning', value: 70 },
  { day: 'Tmrw', period: 'Afternoon', value: 73 },
  { day: 'Tmrw', period: 'Evening', value: 71 },
  { day: 'Wed', period: 'Morning', value: 72 },
  { day: 'Wed', period: 'Afternoon', value: 75 },
  { day: 'Wed', period: 'Evening', value: 73 },
  { day: 'Thu', period: 'Morning', value: 74 },
  { day: 'Thu', period: 'Afternoon', value: 76 },
  { day: 'Thu', period: 'Evening', value: 75 },
  { day: 'Fri', period: 'Morning', value: 75 },
  { day: 'Fri', period: 'Afternoon', value: 77 },
  { day: 'Fri', period: 'Evening', value: 76 },
  { day: 'Sat', period: 'Morning', value: 77 },
  { day: 'Sat', period: 'Afternoon', value: 79 },
  { day: 'Sat', period: 'Evening', value: 78 },
  { day: 'Sun', period: 'Morning', value: 79 },
  { day: 'Sun', period: 'Afternoon', value: 80 },
  { day: 'Sun', period: 'Evening', value: 81 },
];
  
export const healthDataTomorrow = [
  { day: 'Today', period: 'Morning', value: 69 },
  { day: 'Today', period: 'Afternoon', value: 72 },
  { day: 'Today', period: 'Evening', value: 68 },
  { day: 'Tmrw', period: 'Morning', value: 70 },
  { day: 'Tmrw', period: 'Afternoon', value: 73 },
  { day: 'Tmrw', period: 'Evening', value: 71 },
];
  
export const energyData = [
  { day: 'Today', period: 'Morning', value: 75 },
  { day: 'Today', period: 'Afternoon', value: 72 },
  { day: 'Today', period: 'Evening', value: 68 },
  { day: 'Tmrw', period: 'Morning', value: 76 },
  { day: 'Tmrw', period: 'Afternoon', value: 73 },
  { day: 'Tmrw', period: 'Evening', value: 70 },
  { day: 'Wed', period: 'Morning', value: 77 },
  { day: 'Wed', period: 'Afternoon', value: 74 },
  { day: 'Wed', period: 'Evening', value: 71 },
  { day: 'Thu', period: 'Morning', value: 78 },
  { day: 'Thu', period: 'Afternoon', value: 75 },
  { day: 'Thu', period: 'Evening', value: 72 },
  { day: 'Fri', period: 'Morning', value: 80 },
  { day: 'Fri', period: 'Afternoon', value: 77 },
  { day: 'Fri', period: 'Evening', value: 73 },
  { day: 'Sat', period: 'Morning', value: 81 },
  { day: 'Sat', period: 'Afternoon', value: 78 },
  { day: 'Sat', period: 'Evening', value: 74 },
  { day: 'Sun', period: 'Morning', value: 83 },
  { day: 'Sun', period: 'Afternoon', value: 80 },
  { day: 'Sun', period: 'Evening', value: 76 },
];
  
export const energyDataTomorrow = [
  { day: 'Today', period: 'Morning', value: 75 },
  { day: 'Today', period: 'Afternoon', value: 72 },
  { day: 'Today', period: 'Evening', value: 68 },
  { day: 'Tmrw', period: 'Morning', value: 76 },
  { day: 'Tmrw', period: 'Afternoon', value: 73 },
  { day: 'Tmrw', period: 'Evening', value: 70 },
];
  
export const cognitiveData = [
  { day: 'Today', period: 'Morning', value: 83 },
  { day: 'Today', period: 'Afternoon', value: 80 },
  { day: 'Today', period: 'Evening', value: 78 },
  { day: 'Tmrw', period: 'Morning', value: 84 },
  { day: 'Tmrw', period: 'Afternoon', value: 81 },
  { day: 'Tmrw', period: 'Evening', value: 79 },
  { day: 'Wed', period: 'Morning', value: 85 },
  { day: 'Wed', period: 'Afternoon', value: 82 },
  { day: 'Wed', period: 'Evening', value: 80 },
  { day: 'Thu', period: 'Morning', value: 86 },
  { day: 'Thu', period: 'Afternoon', value: 83 },
  { day: 'Thu', period: 'Evening', value: 81 },
  { day: 'Fri', period: 'Morning', value: 87 },
  { day: 'Fri', period: 'Afternoon', value: 84 },
  { day: 'Fri', period: 'Evening', value: 82 },
  { day: 'Sat', period: 'Morning', value: 87 },
  { day: 'Sat', period: 'Afternoon', value: 84 },
  { day: 'Sat', period: 'Evening', value: 82 },
  { day: 'Sun', period: 'Morning', value: 88 },
  { day: 'Sun', period: 'Afternoon', value: 85 },
  { day: 'Sun', period: 'Evening', value: 83 },
];
  
export const cognitiveDataTomorrow = [
  { day: 'Today', period: 'Morning', value: 83 },
  { day: 'Today', period: 'Afternoon', value: 80 },
  { day: 'Today', period: 'Evening', value: 78 },
  { day: 'Tmrw', period: 'Morning', value: 84 },
  { day: 'Tmrw', period: 'Afternoon', value: 81 },
  { day: 'Tmrw', period: 'Evening', value: 79 },
];
  
export const stressData = [
  { day: 'Today', period: 'Morning', value: 42 },
  { day: 'Today', period: 'Afternoon', value: 45 },
  { day: 'Today', period: 'Evening', value: 47 },
  { day: 'Tmrw', period: 'Morning', value: 43 },
  { day: 'Tmrw', period: 'Afternoon', value: 46 },
  { day: 'Tmrw', period: 'Evening', value: 48 },
  { day: 'Wed', period: 'Morning', value: 41 },
  { day: 'Wed', period: 'Afternoon', value: 44 },
  { day: 'Wed', period: 'Evening', value: 46 },
  { day: 'Thu', period: 'Morning', value: 40 },
  { day: 'Thu', period: 'Afternoon', value: 43 },
  { day: 'Thu', period: 'Evening', value: 45 },
  { day: 'Fri', period: 'Morning', value: 39 },
  { day: 'Fri', period: 'Afternoon', value: 42 },
  { day: 'Fri', period: 'Evening', value: 44 },
  { day: 'Sat', period: 'Morning', value: 38 },
  { day: 'Sat', period: 'Afternoon', value: 41 },
  { day: 'Sat', period: 'Evening', value: 43 },
  { day: 'Sun', period: 'Morning', value: 37 },
  { day: 'Sun', period: 'Afternoon', value: 40 },
  { day: 'Sun', period: 'Evening', value: 42 },
];
  
export const stressDataTomorrow = [
  { day: 'Today', period: 'Morning', value: 42 },
  { day: 'Today', period: 'Afternoon', value: 45 },
  { day: 'Today', period: 'Evening', value: 47 },
  { day: 'Tmrw', period: 'Morning', value: 43 },
  { day: 'Tmrw', period: 'Afternoon', value: 46 },
  { day: 'Tmrw', period: 'Evening', value: 48 },
];